export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const POST_LOADING = 'POST_LOADING';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const PRIVATE_MESSAGING_LOADING = 'PRIVATE_MESSAGING_LOADING';
export const GET_PRIVATE_MESSAGES = 'GET_PRIVATE_MESSAGES';
export const GET_PRIVATE_MESSAGE = 'GET_PRIVATE_MESSAGE';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_REPLIES = 'ADD_REPLIES';
export const DELETE_REPLY = 'DELETE_REPLY';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';





